name: デプロイ

on:
  push:
    branches: [ main ]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: リポジトリをチェックアウト
        uses: actions/checkout@v2

      - name: Node.jsをセットアップ
        uses: actions/setup-node@v2
        with:
          node-version: 18
          cache: 'npm'

      - name: 依存パッケージをインストール
        run: npm ci

      - name: ビルド
        run: npm run build

      - name: GitHub Pagesにアップロード
        uses: actions/upload-pages-artifact@v1
        with:
          path: ./dist

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: デプロイ
        id: deployment
        uses: actions/deploy-pages@v1