name: デプロイ

on:
  push:
    branches: [ main ]
  workflow_dispatch:

permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: リポジトリをチェックアウト
        uses: actions/checkout@v2

      - name: Node.jsをセットアップ
        uses: actions/setup-node@v2
        with:
          node-version: 16
          cache: 'npm'

      - name: 依存パッケージをインストール
        run: npm ci

      - name: ビルド
        run: npm run build

      - name: デプロイ
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: dist